[package]
authors = ["yubrot <yubrot@gmail.com>"]
description = "x86 assembler code generator for xten"
edition = "2021"
license = "BSD-3-Clause"
name = "xtencg"
repository = "https://github.com/yubrot/llrl"
version = "0.1.0"

[dependencies]
heapless = "0.7"
once_cell = "1"
regex = "1"
